
server {
    listen 8082;
    server_name localhost;

    brotli on;
    brotli_comp_level 6;
    brotli_static on;
    brotli_types text/plain text/css application/javascript application/json image/svg+xml;

    location /rshb-mbfl/webmodules/shared/ {
        proxy_pass https://test04.rshb.ru$request_uri;
        proxy_set_header Host test04.rshb.ru;
        proxy_ssl_server_name on;
        proxy_ssl_verify off; # временно для отладки
    }

    location /rshb-mbfl/webmodules/cards/ {
        alias /usr/share/nginx/html/;
        index index.html;
        try_files $uri $uri/ /rshb-mbfl/webmodules/cards/index.html;
    }
}
