server {
    listen 8081;
    server_name localhost;

    resolver 8.8.8.8 1.1.1.1 valid=300s;
    resolver_timeout 5s;

    gzip on;
    gzip_static on;
    gzip_types text/plain text/css application/javascript application/json image/svg+xml;

    root /usr/share/nginx/html;

    location /rshb-mbfl/webmodules/shared/ {
        proxy_pass https://test04.rshb.ru$request_uri;
        proxy_set_header Host test04.rshb.ru;
        proxy_ssl_server_name on;
        proxy_ssl_verify off;
    }

    location /rshb-mbfl/webmodules/profile/ {
        alias /usr/share/nginx/html/;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location / {
        proxy_pass https://test04.rshb.ru$request_uri;
        proxy_set_header Host test04.rshb.ru;
        proxy_ssl_server_name on;
        proxy_ssl_verify off;
    }
}
